# Generated by Django 4.1.1 on 2022-09-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0003_education_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='template',
            field=models.CharField(choices=[(1, 'Template 1'), (2, 'Template 2')], default=1, max_length=65, null=True),
        ),
    ]
